### ISSUE TITLE
Npm run build error

### ISSUE THREAD

**Issue by imtrobin** [fairygui/FairyGUI-threejs-example#32]
Hi, when I do npm run build, I get error

npm run build

npv -v 9.6.6

```
> fairygui-three-example@1.0.0 build
> webpack

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\webpack\lib\NormalModule.js:471:10)
    at F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\webpack\lib\NormalModule.js:503:5
    at F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\webpack\lib\NormalModule.js:358:12
    at F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\loader-runner\lib\LoaderRunner.js:133
                if(isError) throw e;
                            ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\webpack\lib\NormalModule.js:471:10)
    at F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\webpack\lib\NormalModule.js:503:5
    at F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\webpack\lib\NormalModule.js:358:12
    at F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at context.callback (F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at makeSourceMapAndFinish (F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\ts-loader\dist\index.js:93:5)
    at successLoader (F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\ts-loader\dist\index.js:74:9)
    at Object.loader (F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\ts-loader\dist\index.js:25:5)
    at LOADER_EXECUTION (F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\loader-runner\lib\LoaderRunner.js:119:14)
    at runSyncOrAsync (F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\loader-runner\lib\LoaderRunner.js:120:4)
    at iterateNormalLoaders (F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at F:\Dev\Cas\External\FairyGUI-threejs-example\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

Node.js v20.2.0

**Comment by kakao014** [comment]
me too, same error

**Comment by xiaoguzhu** [comment]
fix https://github.com/fairygui/FairyGUI-threejs-example/commit/18d9377151953c8474d56ed3b8d035e40634c5b9
